# Generated by Django 3.2.3 on 2024-06-11 04:28

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20240609_0813'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('user__exact', django.db.models.expressions.F('author')), _negated=True), name='prevent_subscription'),
        ),
    ]
